insert into users (email, gender, password, username, wdate) values ('aaa@naver.com', 'MALE', '12341234', '홍길동', now());
insert into users (email, gender, password, username, wdate) values ('bbb@naver.com', 'MALE', '12341234', '김길동', now());
insert into users (email, gender, password, username, wdate) values ('ccc@naver.com', 'MALE', '12341234', '홍동길', now());
insert into users (email, gender, password, username, wdate) values ('ddd@naver.com', 'MALE', '12341234', '홍동동', now());
insert into users (email, gender, password, username, wdate) values ('eee@naver.com', 'MALE', '12341234', '홍길길', now());
insert into users (email, gender, password, username, wdate) values ('ggg@naver.com', 'MALE', '12341234', '이길동', now());
insert into users (email, gender, password, username, wdate) values ('hhh@naver.com', 'MALE', '12341234', '이길동', now());
insert into users (email, gender, password, username, wdate) values ('jjj@naver.com', 'MALE', '12341234', '이길동', now());
insert into users (email, gender, password, username, wdate) values ('kkk@naver.com', 'MALE', '12341234', '이길동', now());